name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint-and-typecheck:
    name: lint & typecheck
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: '22'

      - name: Set up SSH for deploy key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DOM_MUTATOR_ACCESS_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts
        continue-on-error: true # forked repos don't have access, and this is only for experiment-tag
        shell: bash

      - name: Clear yarn cache
        run: yarn cache clean

      - name: Install
        run: yarn install --frozen-lockfile --force

      - name: Restore build output cache
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        id: dist-cache
        with:
          path: |
            packages/analytics-connector/dist
            packages/experiment-browser/dist
            packages/experiment-core/dist
            packages/experiment-tag/dist
            packages/plugin-segment/dist
          key:
            dist-${{ runner.os }}-${{ hashFiles('packages/**/src/**',
            'packages/**/rollup.config.*', 'packages/**/tsconfig.json',
            'yarn.lock') }}
          restore-keys: |
            dist-${{ runner.os }}-

      - name: Build
        if: steps.dist-cache.outputs.cache-hit != 'true'
        run: yarn build

      - name: Lint
        run: yarn lint

      - name: Typecheck
        run: yarn typecheck
