# Creates jira tickets for new github issues to help triage
name: Jira Issue Creator

on:
  issues:
    types: [opened]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Jira
    name: SDK Bot Jira Issue Creation
    steps:
      - name: Login
        uses: atlassian/gajira-login@ca13f8850ea309cf44a6e4e0c49d9aa48ac3ca4c # v3
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

      - name: Create issue
        id: create
        uses: atlassian/gajira-create@1ff0b6bd115a780592b47bfbb63fc4629132e6ec # v3
        with:
          project: ${{ secrets.JIRA_PROJECT }}
          issuetype: Task
          summary: |
            [SDK - experiment-js-client] ${{ github.event.issue.title }}
          description: |
            ${{ github.event.issue.html_url }}
          fields: '{
            "labels": ["experiment-js-client", "sdk-backlog-grooming", "github"]
          }'

      - name: Log created issue
        run: echo "Issue SKY-${{ steps.create.outputs.issue }} was created"
