name: Set up SSH for Deploy Key

on:
  workflow_call:
    inputs:
      deploy_key:
        description: "The deploy key to use"
        required: true
        type: string

jobs:
  setup-ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH for deploy key
        run: |
          mkdir -p ~/.ssh
          echo "${{ inputs.deploy_key }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts
        shell: bash
